# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M Danish Siddiqui
email: mohammaddsiddiqui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A passionate programmer, loves to work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mdanishs.github.com" # the base hostname & protocol for your site
twitter_username: m_danish_s
github_username:  mdanishs

# Build settings
markdown: kramdown
